### ISSUE TITLE
Going to take a crack at installing your keymap. Anything I should know first?

### ISSUE THREAD

**Issue by adrianocr** [rbreaves/xosx#1]
I have a mechnical keyboard that I built (https://i.imgur.com/l5yDhJB.jpg) with a mac keymap. Up until a few weeks ago I used to work exclusively on a MBP so that's why. I'm also extremely used to the mac style keymap and miss it dearly. 

I took a look at your files and I'm on fedora so I can't run your installer but I should be able to manually install everything and move the files where needed. But I was wondering if you ran into any gotchas or things that I should be on the lookout for. 

Here's to hoping I can get my beloved mac keymap working 🍺

**Comment by rbreaves** [comment]
Edit: The installer file is dated, I don't use the xmodmap files or the keyswap.py file. The only files that matter are the xactive.sh and keyswap.service files as it has been simplified down to just using xprop and setxkbmap. Konsole and terminal apps in general are the only reason why I use xactive.sh, to monitor what app I am currently using and disable the macos keymap temporarily as needed. While in Konsole I've manually remapped my keys under "Configure konsole settings" to use my Super/meta key for copy, paste, create new tabs, and other things. I do that because I want the actual Ctrl+C to still end processes in the terminal like normal and to match OSX's terminal keyboard behavior.

(It is possible to sorta remap the SIGINT for the terminal, but I've never found that to be a very good solution, because there are many Ctrl+ terminal based commands that I don't use often but do at times, so I don't want to remap all of that and I think all that custom work would not not carry over into remote ssh and other terminal sessions any ways. It would also create potential havoc for editors or apps like vim, nano, emacs, tmux, etc. Best just to stick with the defaults in the terminal as much as possible and create mappings that don't create confusion, in my opinion. Ends up being simpler to undo macos keymaps, from either xmodmap or setxkbmap, while in the terminal app and specify the Super/Meta shortcut keys as needed. Perhaps your workflow could be different from mine, but from what I recall on macos terminal apps don't necessarily use Command over Ctrl, unlike the GUI based apps.)

----------------------------------------------

Well I need to update this repo, as I am working towards another way of implementing this without using xprop, although in x11 it is the most universally acceptable solution that I have found so far.

If you create a local user based service you can follow this advice here (link below), but I wouldn't worry about binding via "BindsTo=graphical-session.target" or importing anything (aka "systemctl --user import-environment PATH DBUS_SESSION_BUS_ADDRESS"). I could not get that to work. All that I did was create a simple service that runs the xactive.sh script and then added a script here "~/.config/autostart-scripts/autokeyswap.sh" that loads my keyswap service via "systemctl --user start keyswap". I've tried it other ways, but the service would always fail to run on login until I just did the autostart script.

https://superuser.com/questions/759759/writing-a-service-that-depends-on-xorg

Additionally if you want to swap the ctrl, and super key on the right then you will have to go a little further than I have, because honestly I only use the modifier keys on the left of my keyboard 99.999% of the time. And as far as I know there is not a premade config to swap the right keys the same way. You can follow the advice in this blog post if you want to create a custom right side key swap that can be called via setxkbmap.

https://realh.co.uk/wp/linux-keymap-hacking/

The left side keyswap is done via this command "setxkbmap -option ctrl:swap_lwin_lctl" inside the xactive.sh script https://github.com/rbreaves/xosx/blob/master/xactive.sh. And swap_lwin_lctl is built in to the xkbmap of all linux distros by default afaik.

Edit: To undo setxkbmap options just call it again without any options specificed, eg "setxkbmap -option".

Also that is a nice looking keyboard! I don't currently have a mechanical keyboard, besides an old TI-99 (commodore like computer I have lol). I do plan to order one soon though.

**Comment by rbreaves** [comment]
In preparation of making a workable solution for Wayland I am looking into using plasmoids and other plugin extensions of the most popular DE solutions. Xprop and similar x11 based solutions are obviously not going to work with Wayland's new model, which is designed with security in mind. Preparing for wayland is also why I stopped using xmodmap, xkbmap continues to be relevant however, so any future keyboard mods will use setxkbmap and may involve modifications or linking new files in "/usr/share/X11/xkb/symbols/".

I've already forked an existing plasmoid on KDE Plasma 5 as a proof of concept and it does appear to work, granted this is rather specific and is most applicable to people like me who like using global menus.

https://github.com/rbreaves/applet-window-title/commit/ff17e694579a52a9848d6bea87b2d11f22033718

**Comment by adrianocr** [comment]
Hey man I haven't gotten a chance to fully read through and process the above yet. Mondays! 

Just wanted to reply and let you know that you're not talking to yourself. I'll take a look through all the info asap and get back to you. Thanks for the extensive writeup; much appreciated!

**Comment by rbreaves** [comment]
It's all good, I already went back and edited it at the beginning so you can focus on the only 2 files that really matter, from my view lol.

I plan to rewrite the code in the coming days and basically split it to work universally with all distros that use x11, that's easy enough to do at this point and it pretty well does already, the installer just hasn't been updated. The other half will support Wayland and the most popular DE's.

Only other thing I plan to do is make the install as simple as installing brew on a mac, literally copy, paste and enter, because at that point it'll support just about any linux configuration. The only question I may ask during the install is whether the user wants to swap the keys on the left and the right or jest the left, and whether to exclude any particular apps from the keyswap. I may also include pre-built shortcut key files for editors like Sublime Text, Atom and terminals like Konsole, Gnome-terminal, etc.

**Comment by rbreaves** [comment]
I've started work on a new project that'll replace this one called Kinto. The Kinto script is not completed yet, as I am working out all the logic that needs to happen to make sure that everything gets applied correctly for a wide range of keyboards, but if you want the basics here's an outline that may be helpful. (I will be porting and updating my xactive script as well since it'll work universally as long as you're using x11. Wayland will be added later.)

https://github.com/rbreaves/kinto

1.) check for keyboard type in use.
Confirm windows or mac

2.) If Windows keyboard
  setxkbmap -option
  setxkbmap -option altwin:ctrl_alt_win
- If terminal
  setxkbmap -option
  setxkbmap -option altwin:swap_alt_win
  
2B.) If MacOS keyboard
'/usr/bin/setxkbmap -option ctrl:swap_lwin_lctl'
 - if terminal
   '/usr/bin/setxkbmap -option'

2C) If Chromebook keyboard
  setxkbmap -option
  setxkbmap -option ctrl:lalt_lctrl
- if terminal
  setxkbmap -option
  setxkbmap -option altwin:swap_lalt_lwin

Note: lalt_lctrl for chromebooks are custom created symbol files that are in the Kinto repo and will be loaded via specific commands which I will be adding soon.

**Comment by rbreaves** [comment]
Kinto in the dev branch is functional, at least on my chromebook and with the swap option, xactive.sh enabled.

The script should work for non-swapping behaviors as well, but my focus is on making sure the keymap changes between terminals and gui based apps.

https://github.com/rbreaves/kinto/tree/dev

If you'd prefer to implement the same solution though and without using my installer to do so then these commands are all you really need and you can add them to whatever system files you want like ~/.Xsession or ~/.xinitrc so the keymaps apply on login. I've also tested it with an actual Apple keyboard and changing the swap_opt_cmd to 1 is important for consistent keymapping to apply between windows based laptop keys and an Apple keyboard or a macbook keyboard.

```
# permanent apple keyboard update
echo "options hid_apple swap_opt_cmd=1" >> /etc/modprobe.d/hid_apple.conf
update-initramfs -u -k all

# Windows and Mac keyboards - GUI
echo '1' > /sys/module/hid_apple/parameters/swap_opt_cmd
setxkbmap -option;setxkbmap -option altwin:ctrl_alt_win

# Windows and Mac keyboards - Term
echo '1' > /sys/module/hid_apple/parameters/swap_opt_cmd
setxkbmap -option;setxkbmap -option altwin:swap_alt_win
```
